name: deploy-book  
# Runs when code is pushed to the master or main branch. 
on: 
  push: 
    branches: 
    - master 
    - main 
# This job installs dependencies, builds the book, and pushes it to `gh-pages` 

jobs: 
  deploy-book: 
    runs-on: ubuntu-latest 
    permissions: 
      pages: write 
      id-token: write 
    steps: 
    - uses: actions/checkout@v3 

    # In this example, I needed the glpk and cbc executables so I install them on this VM 
    - name: install glpk and cbc 
      run: | 
        sudo apt update 
        sudo apt-get install -y -qq glpk-utils 
        sudo apt-get install -y -qq coinor-cbc 
      

  # Installing another dependency (Ipopt) 
    - name: install ipopt 
      run: | 
        sudo apt update 
        sudo pip install idaes-pse --pre 
        idaes get-extensions --to ./solvers 

    # Set up python env and install requirements.txt folder 
    - name: Set up Python 3.11 
      uses: actions/setup-python@v4 
      with: 
        python-version: 3.11 
    - name: Install dependencies 
      run: | 
        pip install -r requirements.txt 

    - name: cache executed notebooks 
      uses: actions/cache@v3 
      with: 
        path: _build/.jupyter_cache 
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }} 

    # Build the book 
    - name: Build the book 
      run: | 
        jupyter-book build . 
        
    # Upload the book's HTML as an artifact 
    - name: Upload artifact 
      uses: actions/upload-pages-artifact@v2 
      with: 
        path: "_build/html" 

    # Deploy the book's HTML to GitHub Pages 
    - name: Deploy to GitHub Pages 
      id: deployment 
      uses: actions/deploy-pages@v2 
